baseURL = "https://ttti.cc"
title = "极限玩家"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # 自动检测是否包含 中文\日文\韩文
paginate = 8              # 首页每页显示的文章数
rssLimit = 20             # 限制 Rss 文章输出数量
disqusShortname = "extreme-1" # disqus_shortname
googleAnalytics = "G-XK6SLX411H" # UA-XXXXXXXX-X
copyright = "极限玩家"     # 默认为下面配置的author.name ↓

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"  # Default language to use
[languages.en]
  languageCode = "en"

[Languages.zh-cn]
  languageCode = "zh-cn"

[author]
  name = "南极神"        # 必需
  url = "/about"        # 可选

[sitemap]               # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]] # 配置目录
  name = "首页"
  weight = 10
  identifier = "home"
  pageref = "/"
[[menu.main]]
  name = "存档"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  pageref = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  pageref = "/categories/"
[[menu.main]]
  name = "极限搜索"
  weight = 50
  url = "/so.html"

[params]
  since = "2018" # 站点建立时间
  homeFullContent = false   # 如果为 false ，在主页上显示帖子摘要。否则显示完整的内容。
  rssFullContent = true     # 如果是错误的，则rss feed而不是摘要

  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "极限玩家" # 默认值: 上面设置的title值
  keywords = ["极限玩家", "极限玩家博客", "极限博客", "南极神"]
  description = "极限玩家博客"

  # 使用的日期格式，可以参阅：https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  toc = true  # 是否开启目录
  photoswipe = true  # see https://github.com/dimsemenov/PhotoSwipe  # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '由<a href="https://ttti.cc" target="_blank">极限玩家</a>驱动'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']   # 如果为 ['custom.css'], 则读取 '/static/css/custom.css' file
  customJS = []    # 如果为 ['custom.js'], 则读取 '/static/js/custom.js' file

  [params.social] # 社交链接
    a-email = "mailto:nanjishen@outlook.com"
    h-weibo = "https://weibo.com/nanjishen"
    q-bilibili = "https://space.bilibili.com/8965770/"